---
- name: Opdracht 2 - Variabelen gebruiken
  hosts: all
  become: yes
  vars:
    motd_message: "Welkom bij het lab"

  tasks:
    - name: Zet welkomstbericht in /etc/motd
      copy:
        content: "{{ motd_message }}"
        dest: /etc/motd

    - name: Maak /etc/app.conf met app_name uit inventory
      copy:
        content: "Application = {{ app_name }}"
        dest: /etc/app.conf

    - name: Voer uname -r uit en registreer in kernel_version
      command: uname -r
      register: kernel_version

    - name: Schrijf kernel versie naar /tmp/kernel.txt
      copy:
        content: "{{ kernel_version.stdout }}"
        dest: /tmp/kernel.txt

    - name: Schrijf distributienaam naar /tmp/facts.txt
      copy:
        content: "{{ ansible_distribution }}"
        dest: /tmp/facts.txt
