---
- name: Opdracht 3 - Voorwaardelijke taken
  hosts: all
  become: true

  tasks:

    - name: Taak alleen voor Ubuntu
      debug:
        msg: "Dit is een Ubuntu distributie"
      when: ansible_distribution == "Ubuntu"

    - name: Taak alleen voor Red Hat
      debug:
        msg: "Dit is een Red Hat distributie"
      when: ansible_distribution == "RedHat"

    - name: Controleer of /etc/hosts bestaat
      stat:
        path: /etc/hosts
      register: hosts_file

    - name: Fail als /etc/hosts niet bestaat
      fail:
        msg: "/etc/hosts bestaat niet!"
      when: not hosts_file.stat.exists
      failed_when: not hosts_file.stat.exists

    - name: Echo hallo zonder changed
      command: echo hallo
      changed_when: false
